### ISSUE TITLE
[Bug]: Credit - Dans une page de transition

### ISSUE THREAD

**Issue by Tibeno88** [sfeir-open-source/sfeir-school-theme#107]
### Describe the bug

Pour un slide de transition, si on ajoute pas la classe "quote-slide", les crédits ne se trouvent pas en bas de page.
Il va se retrouver centrer sur la page en horizontal mais il se passe juste en dessous du dernier bloc

### Expected behavior

Avoir le bloc de citation tout en bas de page comme sur les slides classiques

### Screenshots

![image](https://github.com/sfeir-open-source/sfeir-school-theme/assets/24879275/6b7f81f3-adfb-4e30-82e6-44cc6f0eb9f2)

**Comment by jefBinomed** [comment]
sera traité ici https://github.com/TalkControl/talk-control-revealjs-extensions/issues/6
