### ISSUE TITLE
[Bug]: [a11y] remove style from alt 

### ISSUE THREAD

**Issue by roxyska** [sfeir-open-source/sfeir-school-theme#115]
### Describe the bug

alt attribute is used to style some content. Alt attributes should only be used for accessibility concerns. It provides informations for users who can't see an images (if blind or has bad network for example).
eg. images on speaker slides : 
Markdown: `![speaker](./images/xxx.jpg)`
CSS: `.speaker-slide img[alt*=speaker]`

### Expected behavior

Markdown: `![homme blanc avec les cheveux court et les yeux bleus](./images/xxx.jpg)<!-- .element: class="speaker"-->`
CSS: `.speaker-slide img.speaker { ... }`

### Additional context

Documentation to create slides should be updated accordingly

**Comment by jefBinomed** [comment]
sera traité ici : https://github.com/TalkControl/talk-control-revealjs-extensions/issues/4
