### ISSUE TITLE
Alignement de badges et badge multiples

### ISSUE THREAD

**Issue by Sourcemancien** [sfeir-open-source/sfeir-school-theme#21]
La version actuelle ne permet pas de gérer plusieurs badges à la fois pour un speaker.

Exemple le code suivant
```
<!-- .slide: class="speaker-slide" -->

# Présentation

![speaker](./assets/images/speakers/T03L707TH-U3P2A0CBC-f24698eab2ef-512.jpeg)
![company](./assets/images/logo_sfeir_bleu_orange.png)
![badge](./assets/images/badges/g4778d033d9_0_0.png)
![badge](./assets/images/badges/g4778d033d9_0_1.png)

<h2> Antoine<span> Meausoone</span></h2>

### Cloud DevOps 
<!-- .element: class="icon-rule icon-first" -->

### @Ameausoone
<!-- .element: class="icon-twitter icon-second" -->
```

les badges se superposent :

![image](https://user-images.githubusercontent.com/844394/78537211-64305680-77ef-11ea-8388-1e76c54b2522.png)

En fusionnant les images pour produire un seul "badge", un problème d'alignement se produit (car le ratio de l'image n'est pas du 1:1 ?)

![image](https://user-images.githubusercontent.com/844394/78537497-e02a9e80-77ef-11ea-91a9-d6d09dc61325.png)

Mais le problème d'alignement peut aussi avoir lieu avec un seul badge, si l'image est trop petite je suppose:
![image](https://user-images.githubusercontent.com/844394/78537922-8080c300-77f0-11ea-93a7-5a02ec689c32.png)

image du badge solo:
![image](https://user-images.githubusercontent.com/844394/78538133-d81f2e80-77f0-11ea-86f0-a01a89c39259.png)

**Comment by Sourcemancien** [comment]
Ajout concernant les 2 badges fusionnés, le positionnement s'améliore si je rattrape le ratio d'image vers du 1:1
mais les badges sont toujours réduits:
![image](https://user-images.githubusercontent.com/844394/78539011-2d0f7480-77f2-11ea-9c82-0b1fcacd4b16.png)

**Comment by jefBinomed** [comment]
Merci, je vais proposer un truc comme les titres

**Comment by jefBinomed** [comment]
fix with https://github.com/sfeir-open-source/sfeir-school-theme/pull/35
