### ISSUE TITLE
Fragment animation broken for two-column-layout

### ISSUE THREAD

**Issue by devsheder** [sfeir-open-source/sfeir-school-theme#22]
Hi,
I tried to use fragment animation to animate items within slides using `two-column-layout`class.
Here is an example :
```mardown
<!-- .slide: class="two-column-layout" -->

# Un problème de this ...

##--##

<!-- .slide: class="with-code" -->

<pre class="fragment" data-fragment-index="1"><code data-trim class="javascript">

   var f = {
      nums: [1, 2, 3, 4, 5, 6],
      even: [],
      each() {
        this.nums.forEach(function(v) {
          if (v % 2 === 0)
            this.even.push(v);//ERROR
        });
      }
   };
   f.each();
</code></pre>

##--##

<!-- .slide: class="with-code" -->

<pre class="fragment" data-fragment-index="2"><code data-trim class="javascript">
//Correction

var f = {
    nums: [1, 2, 3, 4, 5, 6],
    even: [],
    each() {
    var self = this;
    this.nums.forEach(function(v) {
        if (v % 2 === 0)
        self.even.push(v);
    });
    }
};
f.each();
</code></pre>
```
The first fragment, `pre`tag with `data-fragment-index="1"`, is broken : it shows immediately when slide shows. No problem with the second fragment with `data-fragment-index="2"`.
After several tests, it appears that the left column of the layout shows immediately when slide shows (no probleme for the right column with several fragments).

Thanks !

**Comment by jefBinomed** [comment]
Je dois revoir le two-column-layout tout court...., ça résoudrait le pb :p

**Comment by Xartok** [comment]
J'ai créé une autre issue également liée au two column layout (#51) à propos de la sélection du texte dans les slides

**Comment by jefBinomed** [comment]
Fix avec [#ff5dba5](https://github.com/sfeir-open-source/sfeir-school-theme/commit/ff5dba54967d55c6c3b08e1e04e5ef5ed71fd395)
