### ISSUE TITLE
Faire ressortir l'inline code du texte standard

### ISSUE THREAD

**Issue by mJehanno** [sfeir-open-source/sfeir-school-theme#23]
<img width="1678" alt="Screenshot 2020-04-06 at 16 20 57" src="https://user-images.githubusercontent.com/9280964/78568842-faca3b00-7822-11ea-953c-e1f363a40149.png">

le code markdown utilisé pour générer le contenu de l'image : 

``` markdown
<br><br>
- attribut `draggable=true` sur l'élément html.
<br><br>
- `ondragstart` event sur l'élément draggable.
<br><br>
- `ondrop` event dans la zone de dépot.
<br><br>
- `ondraghover` event sur la zone de dépot.
```

Comme on peut le voir le rendu du inline-code reste neutre et ne se démarque pas vraiment du reste. Un work-around consiste à mettre une span avec du style autour du bloc de code mais il y a peut-être moyen de simplifier ça ? 🤔

**Comment by jefBinomed** [comment]
ah oui, du coup, l'idée serait d'avoir une sorte de background légé autour ?

**Comment by mJehanno** [comment]
Yup un truc qui dénote, pour la slide pwa pour le moment je suis partis sur ça autour du bloc de code :

```html
<span style="background:grey; color: white; padding: 0 0.5em 0 0.5em;">`inline-code`</span>
```
