### ISSUE TITLE
Ajouter une méta pour avoir du background de code dark

### ISSUE THREAD

**Issue by jefBinomed** [sfeir-open-source/sfeir-school-theme#27]
Au lieu d'avoir systématiquement un background de code light ou alors tout l'écran en dark, il pourrait être intéressante d'avoir l'étape intermédiaire à savoir, le slide en blanc et le code avec un background dark et donc avoir une meta du type with-code-bg-dark

**Comment by bogaertg** [comment]
done by cd34b990309b1eadd7a408c2a6a504b527470b68
