### ISSUE TITLE
Compléter la doc

### ISSUE THREAD

**Issue by jefBinomed** [sfeir-open-source/sfeir-school-theme#28]
Compléter la doc avec les possibilités offertes par le langage markdown et son rendu.

De même ajouter aussi la même chose pour les métas données revealJS. 

Compléter donc la démo et surtout le README.

**Comment by sadstag** [comment]
J'ajoute qu'il y un léger soucis avec la démo : 

sur un fresh clone du repo un npm start lance la démo mais  : http://127.0.0.1:62740/demo/dist/css/sfeir-school-theme.css not found
il faut faire un npm run build avant pour regler le probleme.

**Comment by jefBinomed** [comment]
Fix avec [#ff5dba5](https://github.com/sfeir-open-source/sfeir-school-theme/commit/ff5dba54967d55c6c3b08e1e04e5ef5ed71fd395)
