### ISSUE TITLE
[V2.1] Chevauchement des titres

### ISSUE THREAD

**Issue by geromegrignon** [sfeir-open-source/sfeir-school-theme#47]
La mise à jour du theme en V2.1 provoque un chevauchement du texte sur les slides incluant des balises h1 à h3 à cause du passage du *margin-top* de `-10px` à `-90px`.

Exemples identifié sur la school PWA: 

![image](https://user-images.githubusercontent.com/32737308/83957143-a44e9c80-a865-11ea-9c34-842da134f857.png)

![image](https://user-images.githubusercontent.com/32737308/83957107-32765300-a865-11ea-8e81-baedd0d9d5b9.png)

**Comment by jefBinomed** [comment]
Fix avec [#ff5dba5](https://github.com/sfeir-open-source/sfeir-school-theme/commit/ff5dba54967d55c6c3b08e1e04e5ef5ed71fd395)
