### ISSUE TITLE
To fix for V3.0.0

### ISSUE THREAD

**Issue by jefBinomed** [sfeir-open-source/sfeir-school-theme#78]
- [x] Fixer les vunerabilities npms
- [x] Ajouter un surlignage sur les liens (blanc quand fond sombre, bleu ou vert si fond blanc)
- [x] S'assurer de la possibilité de la source en bleu ou vert sur un slide de quote

**Comment by rlespinasse** [comment]
Pour la slide speaker, le guide de migration parle de "icon-role", hors seul "icon-rule" mets le role dans un encadré de couleur (ancien fonctionnement).

**Comment by rlespinasse** [comment]
Sur les slide `with-code`, le bloc dépasse par le bas, et sur les blocs avec beaucoup de code, on ne voit pas la fin si on a mis des titres dans la slide.

**Comment by rlespinasse** [comment]
Si on utilise la fonction de highlight de code, on perds l'indentation du code

**Comment by rlespinasse** [comment]
Les tables ont une taille de texte plus petite que le theme v2.

**Comment by rlespinasse** [comment]
Pas que `v3`, mais `list-fragment` ne fonctionne pas sur les lignes en multilignes

Fonctionne

```md
- Texte 1 ![](./assets/images/image1.png)
- Texte 2 ![](./assets/images/image2.png)
<!-- .element: class="list-fragment" -->
```

Fonctionne pas

```md
- Texte 1
  ![](./assets/images/image1.png)
- Texte 2
  ![](./assets/images/image2.png)
<!-- .element: class="list-fragment" -->
```

**Comment by jefBinomed** [comment]
> Pour la slide speaker, le guide de migration parle de "icon-role", hors seul "icon-rule" mets le role dans un encadré de couleur (ancien fonctionnement).

ça, je pense que c'est une coquille de ma part

**Comment by jefBinomed** [comment]
> Sur les slide `with-code`, le bloc dépasse par le bas, et sur les blocs avec beaucoup de code, on ne voit pas la fin si on a mis des titres dans la slide.
> 
> Cela provoque aussi un souci si plusieurs blocs de code sont utilisés sur une même slide.

J'avais une feinte mise en place sur la PWA pour contrer ça, je vais ajouter cette feinte directement dans le modèle par défaut

**Comment by jefBinomed** [comment]
> Les tables ont une taille de texte plus petite que le theme v2.

Hum... faudra que je compare mais après, je pense pas forcément retoucher ça pour coller avec la charte

**Comment by jefBinomed** [comment]
> `list-fragment` ne fonctionne pas sur les lignes en multilignes
> 
> Fonctionne
> 
> ```lisp
> - Texte 1 ![](./assets/images/image1.png)
> - Texte 2 ![](./assets/images/image2.png)
> 
> ```
> 
> Fonctionne pas
> 
> ```lisp
> - Texte 1
>   ![](./assets/images/image1.png)
> - Texte 2
>   ![](./assets/images/image2.png)
> 
> ```
> 
> > Je ne suis pas sur que ce comportement n'était pas déjà présent en v2.

ça, c'est en effet un truc contraignant du script qui convertit le markdown... Dans ta deuxième version, il te met des balises <p> partout alors que dans la première, il ratache bien proprement tout dans un seul et même <p>. Donc, je pourrais rien y faire
