### ISSUE TITLE
Ajouter syntax highlighting de reveal

### ISSUE THREAD

**Issue by jefBinomed** [sfeir-open-source/sfeir-school-theme#9]
Ajouter un moyen d'utiliser : https://github.com/hakimel/reveal.js/#code-syntax-highlighting (line number highlights)

**Comment by elebeaup** [comment]
Cette fonctionnalité est supporté nativement en reveal.js 4 https://revealjs.com/markdown/#syntax-highlighting

**Comment by elebeaup** [comment]
#48
