### ISSUE TITLE
[Bug]: Missing dependency

### ISSUE THREAD

**Issue by shepard8** [sfeir-open-source/sfeir-school-theme#94]
### Describe the bug

The images (e.g., favicon) won't load.

### Reproduction steps

Create a new project following exactly the instructions given in the README.md file, and check the Javascript console, there will be errors because web_modules/sfeir-school-theme/images/favicon.png (and favicon-32.png) are not found.

### Expected behavior

There should be no error in the console

### Additional context

This problem can be solved by installing package webpack.

My guess is that it was a dependency for RevealJS in the past but that it's no longer the case.

webpack should be added as a dependency to the theme.

**Comment by jefBinomed** [comment]
c'est normal
